### ISSUE TITLE
访问者模式

### ISSUE THREAD

**Issue by skyflysun** [fanerge/fanerge.github.io#1]
冒昧的问下，因为自己不是很懂。
用元素类的accept 方法去调用visitor的vistior 方法。这样做的话为啥不直接用元素实例拿到方法去做一些事情哪？
按照你上面定义的话，感觉好像增加了复杂度。
能不能解下惑？？感谢

**Comment by fanerge** [comment]
你好，这样做主要是满足单一职责原则，将我们易变操作封装到元素类中，仅仅通过元素类的 accept 方法决定哪一个访问者可以访问我们的元素类。
